app:
  name: xrfq3

log:
  level: INFO
  suffix: log
  prefix: xrfq3
  output: .logs

database:
  postgres:
    port: 5432
    host: "127.0.0.1"
    name: "xrf37ilQdb"
    username: "postgres"
    password: "password"
  cassandra:
    host: "localhost"
    user: "cassandra"
    password: "cassandra"
  timescale:
    name: local
  redis:
    name: local
