log:
  level: DEBUG

database:
  postgres:
    require_ssl: false
  cassandra:
    ssl: false
    port: 9044
    host: "127.0.0.1"
    connect_timeout: 5
    replication_factor: 1
    keyspace: "xrf_q3_block"
  timescale:
    require_ssl: false
  redis:
    port: 6379
    database: 0
    username: ''
    password: ''
    uri_scheme: local
    require_tls: false
    hostname: 127.0.0.1

server:
  grpc:
    port: 50053
    timeout: 60
