log:
  level: DEBUG

database:
  postgres:
    require_ssl: false
  cassandra:
    ssl: false
    port: 9044
    connect_timeout: 5
    replication_factor: 1
  timescale:
    require_ssl: false
  redis:
    name: local
