name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_service_on_macos_specific_version:
    runs-on: macos-13 # Changed from macos-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Code (Placeholder)
        uses: actions/checkout@v4

      - name: Confirm Service Initialization
        run: |
          echo "Job has started on macos-13. If Docker was not found for services, this step might not even run or the job would have failed earlier."
          echo "Waiting a few seconds for service health checks..."
          sleep 30
          echo "Attempting to see if PostgreSQL port is available (implies service started)..."
          if nc -z localhost 5432; then
            echo "SUCCESS: PostgreSQL is listening on localhost:5432"
          else
            echo "FAILURE: PostgreSQL NOT listening on localhost:5432. Service might not have started."
            exit 1
          fi
