name: Rust

on: [ workflow_dispatch ] # Allows manual triggering

jobs:
  test_service_on_macos:
    runs-on: macos-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Service Should Be Initializing
        run: echo "Job started, PostgreSQL service should have attempted to initialize."

      - name: Wait and Check Port
        run: |
          echo "Waiting 30s for service to be fully up..."
          sleep 30 
          echo "Checking if PostgreSQL port is accessible on localhost..."
          if nc -z localhost 5432; then
            echo "SUCCESS: PostgreSQL is listening on localhost:5432"
          else
            echo "FAILURE: PostgreSQL NOT listening on localhost:5432"
            # If it failed because docker wasn't found, this step might not even be reached
            # or the service wouldn't be running.
            exit 1
          fi
