name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ] # Test on both Linux and macOS

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # caching Cargo dependencies: https://github.com/actions/cache
      - name: Cache Cargo registry and index
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable # Later: the app's your specific toolchain version

      - name: Install Prerequisites (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "Starting: Install Prerequisites"
          sudo apt-get update -vv # Increased verbosity
          sudo apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl gnupg lsb-release
          echo "Finished: Install Prerequisites"

      - name: Add DataStax GPG Key (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "Starting: Add DataStax GPG Key"
          # Added --connect-timeout and --max-time to curl
          # Increased verbosity for gpg
          curl --verbose --show-error --connect-timeout 15 --max-time 60 -fsSL https://downloads.datastax.com/cpp-driver/repo/repo_key | sudo gpg --verbose --dearmor -o /usr/share/keyrings/datastax-archive-keyring.gpg
          # Verify the key file was created
          sudo ls -l /usr/share/keyrings/datastax-archive-keyring.gpg
          echo "Finished: Add DataStax GPG Key"

      - name: Add DataStax APT Repository (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "Starting: Add DataStax APT Repository"
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/datastax-archive-keyring.gpg] https://downloads.datastax.com/cpp-driver/ubuntu/$(lsb_release -sc) $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/datastax.sources.list > /dev/null
          # Verify the repo file was created
          sudo cat /etc/apt/sources.list.d/datastax.sources.list
          echo "Finished: Add DataStax APT Repository"

      - name: Update APT Cache for DataStax Repo (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "Starting: Update APT Cache for DataStax Repo"
          sudo apt-get update -vv # Increased verbosity
          echo "Finished: Update APT Cache for DataStax Repo"

      - name: Install Cassandra C++ Driver (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "Starting: Install Cassandra C++ Driver"
          sudo apt-get install -y --no-install-recommends libdatastax-cpp-driver-dev libuv1-dev libssl-dev pkg-config
          echo "Finished: Install Cassandra C++ Driver"

      - name: Install Cassandra C++ Driver (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update # Ensure brew is updated
          # Install the driver and its dependencies
          brew install cassandra-cpp-driver libuv openssl pkg-config

      - name: Set Build Environment Variables (Linux)
        if: runner.os == 'Linux'
        run: |
          # Use crate-specific vars if you found them (replace VAR_NAME):
          # echo "CASSANDRA_SYS_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          # echo "CASSANDRA_SYS_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
          
          # ---- OR ---- Use general variables (adjust paths if needed for specific Linux distros)
          echo "LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "CPATH=/usr/include:$CPATH" >> $GITHUB_ENV
          echo "*** Linux ENV Vars Set ***" # Add for debugging

      - name: Set Build Environment Variables (macOS)
        if: runner.os == 'macOS'
        run: |
          # Use crate-specific vars if you found them (replace VAR_NAME):
          # echo "CASSANDRA_SYS_LIB_DIR=$(brew --prefix)/lib" >> $GITHUB_ENV
          # echo "CASSANDRA_SYS_INCLUDE_DIR=$(brew --prefix)/include" >> $GITHUB_ENV
          
          # ---- OR ---- Use general variables
          echo "LIBRARY_PATH=$(brew --prefix)/lib:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "CPATH=$(brew --prefix)/include:$CPATH" >> $GITHUB_ENV
          echo "*** macOS ENV Vars Set ***" # Add for debugging

      - name: Build Project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
